In [73]:
import pandas as pd
import warnings
import uuid

warnings.filterwarnings("ignore")

In [74]:
data = pd.read_csv('../data/staging/contrataciones_publicas_staging.csv')
data

,nombre_entidad,nit_entidad,departamento,ciudad,orden,sector,rama,entidad_centralizada,proceso_de_compra,id_contrato,...,nombre_supervisor,tipo_de_documento_supervisor,numero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,numero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo,duracion_valor,duracion_unidad
0,PERSONERIA MUNICIPAL DE PEREIRA,8914800302,Risaralda,Pereira,Territorial,No aplica/No pertenece,Corporación Autónoma,Descentralizada,CO1.BDOS.9064606,CO1.PCCNTR.8560835,...,JUANA VALENTINA MEJIA LOPEZ,Cédula de Ciudadanía,1088307105,NO DEFINIDO,No definido,No definido,No,No definido,30.0,Dia(s)
1,SENA REGIONAL TOLIMA 1,899999034,Tolima,Ibagué,Nacional,Trabajo,Ejecutivo,Centralizada,CO1.BDOS.5531221,CO1.PCCNTR.5846057,...,FAVIO ARMANDO MEDINA CALDERON,Cédula de Ciudadanía,88158809,JUAN CAMILO SOTO DIAZ,Cédula de Ciudadanía,93413769,No,No definido,313.0,Dia(s)
2,GOBERNACION DEL CAQUETA,800091594,Caquetá,No Definido,Territorial,No aplica/No pertenece,Ejecutivo,Centralizada,CO1.BDOS.1437148,CO1.PCCNTR.1839307,...,LINA MARCELA MANJARRES MENDEZ,Cédula de Ciudadanía,40611537,NO DEFINIDO,No definido,No definido,No,No definido,113.0,Dia(s)
3,SENA REGIONAL META GRUPO DE APOYO ADMINISTRATI...,899999034,Meta,No Definido,Nacional,Trabajo,Ejecutivo,Descentralizada,CO1.BDOS.9070612,CO1.PCCNTR.8627960,...,ADRIANA YOLIMA MORALES RAMIREZ,Cédula de Ciudadanía,52960794,NO DEFINIDO,No definido,No definido,No,No definido,17.0,Dia(s)
4,MINISTERIO DEL INTERIOR,830114475,Distrito Capital de Bogotá,Bogotá,Nacional,interior,Ejecutivo,Centralizada,CO1.BDOS.7115693,CO1.PCCNTR.7096520,...,NO DEFINIDO,No definido,No definido,NO DEFINIDO,No definido,No definido,No,No definido,29.0,Dia(s)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1837,MINISTERIO DEL INTERIOR,830114475,Distrito Capital de Bogotá,Bogotá,Nacional,interior,Ejecutivo,Centralizada,CO1.BDOS.289473,CO1.PCCNTR.277825,...,NO DEFINIDO,No definido,No definido,NO DEFINIDO,No definido,No definido,No,No definido,NaN,NaN
1838,SENA REGIONAL DISTRITO CAPITAL GRUPO ADMINISTR...,899999034,Distrito Capital de Bogotá,Bogotá,Nacional,Trabajo,Ejecutivo,Descentralizada,CO1.BDOS.4068013,CO1.PCCNTR.4689252,...,CLAUDIA PATRICIA GUEVARA ARMENTA,Cédula de Ciudadanía,49769961,NO DEFINIDO,No definido,No definido,No,No definido,225.0,Dia(s)
1839,MUNICIPIO DE ENVIGADO,890907106,Antioquia,Envigado,Nacional,Cultura,Ejecutivo,Centralizada,CO1.BDOS.9340152,CO1.PCCNTR.9153527,...,DIEGO ALEJANDRO DUQUE BERNAL,Cédula de Ciudadanía,1.037.588.116,NO DEFINIDO,No definido,No definido,No,No definido,317.0,Dia(s)
1840,DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BA...,890102018,Atlántico,Barranquilla,Territorial,Servicio Público,Ejecutivo,Descentralizada,CO1.BDOS.2547893,CO1.PCCNTR.3229533,...,JAIME EDUARDO NIÑO FLOREZ,Cédula de Ciudadanía,77178147,NO DEFINIDO,No definido,No definido,No,No definido,6.0,Mes(es)
1841,INSTITUTO MUNICIPAL DE DEPORTE Y RECREACION DE...,822000538,Meta,Villavicencio,Territorial,deportes,Ejecutivo,Centralizada,CO1.BDOS.3260025,CO1.PCCNTR.4010790,...,LUIS FERNANDO DUQUE ORTIZ,Cédula de Ciudadanía,86085671,NO DEFINIDO,No definido,No definido,No,No definido,115.0,Dia(s)

### Dim Geografía

In [75]:
dim_geografia = data[['departamento', 'ciudad']].drop_duplicates().reset_index(drop=True)
dim_geografia["id_geografia"] = dim_geografia.apply(lambda _: str(uuid.uuid4()), axis=1)
dim_geografia = dim_geografia[["id_geografia", "departamento", "ciudad"]]
dim_geografia

,id_geografia,departamento,ciudad
0,a0873382-08c5-4535-ab71-6351f4f974c1,Risaralda,Pereira
1,55c91753-b900-484c-92f6-dc3bc0acadce,Tolima,Ibagué
2,f0e48572-3f42-429b-a88c-580730891487,Caquetá,No Definido
3,b21b339b-392f-437e-8ccc-92f1a4f79785,Meta,No Definido
4,cbaea542-c3b3-4700-bf9d-3dc480472d2f,Distrito Capital de Bogotá,Bogotá
...,...,...,...
226,01199ed7-8a5e-43bc-979b-91a64dc9dffb,Caquetá,San Vicente Del Caguán
227,ac948350-df5f-4233-a894-b123b6081047,Antioquia,Guatape
228,6ca01f31-dd9b-4a09-983d-95d37ae6b6dd,Caldas,Chinchiná
229,5358682c-1df9-45f0-a5c3-ab2811aa2e7d,Antioquia,Támesis
230,e58425d7-6357-4eb5-b923-77e54cbb8a9c,Cundinamarca,Albán

### Dim Fecha

In [76]:
dim_fecha_firma = data[['fecha_de_firma']].drop_duplicates().sort_values(by="fecha_de_firma").reset_index(drop=True)

dim_fecha_firma["año"] = pd.to_datetime(dim_fecha_firma['fecha_de_firma'], errors='coerce').dt.year
dim_fecha_firma["mes"] = pd.to_datetime(dim_fecha_firma['fecha_de_firma'], errors='coerce').dt.month
dim_fecha_firma["día"] = pd.to_datetime(dim_fecha_firma['fecha_de_firma'], errors='coerce').dt.day
dim_fecha_firma = dim_fecha_firma.rename(columns={'fecha_de_firma': 'fecha'})

dim_fecha_inicio = data[['fecha_de_inicio_del_contrato']].drop_duplicates().sort_values(by="fecha_de_inicio_del_contrato").reset_index(drop=True)
dim_fecha_inicio["año"] = pd.to_datetime(dim_fecha_inicio['fecha_de_inicio_del_contrato'], errors='coerce').dt.year
dim_fecha_inicio["mes"] = pd.to_datetime(dim_fecha_inicio['fecha_de_inicio_del_contrato'], errors='coerce').dt.month
dim_fecha_inicio["día"] = pd.to_datetime(dim_fecha_inicio['fecha_de_inicio_del_contrato'], errors='coerce').dt.day
dim_fecha_inicio = dim_fecha_inicio.rename(columns={'fecha_de_inicio_del_contrato': 'fecha'})

dim_fecha_fin = data[['fecha_de_fin_del_contrato']].drop_duplicates().sort_values(by="fecha_de_fin_del_contrato").reset_index(drop=True)
dim_fecha_fin["año"] = pd.to_datetime(dim_fecha_fin['fecha_de_fin_del_contrato'], errors='coerce').dt.year
dim_fecha_fin["mes"] = pd.to_datetime(dim_fecha_fin['fecha_de_fin_del_contrato'], errors='coerce').dt.month
dim_fecha_fin["día"] = pd.to_datetime(dim_fecha_fin['fecha_de_fin_del_contrato'], errors='coerce').dt.day
dim_fecha_fin = dim_fecha_fin.rename(columns={'fecha_de_fin_del_contrato': 'fecha'})

print(dim_fecha_firma.head(5))
print(dim_fecha_inicio.head(5))
print(dim_fecha_fin.head(5))

        fecha   año  mes  día
0  2017-01-23  2017    1   23
1  2017-01-27  2017    1   27
2  2017-04-07  2017    4    7
3  2017-05-01  2017    5    1
4  2017-07-05  2017    7    5
        fecha   año  mes  día
0  2017-01-23  2017    1   23
1  2017-01-27  2017    1   27
2  2017-03-01  2017    3    1
3  2017-03-30  2017    3   30
4  2017-04-07  2017    4    7
        fecha   año  mes  día
0  2017-06-29  2017    6   29
1  2017-09-06  2017    9    6
2  2017-11-30  2017   11   30
3  2017-12-02  2017   12    2
4  2017-12-10  2017   12   10

### Dim Detalles del Contrato

In [77]:
dim_detalles = data[['id_contrato', 'referencia_del_contrato', 'estado_contrato', 'codigo_de_categoria_principal', 'descripcion_del_proceso', 'tipo_de_contrato', 'modalidad_de_contratacion', 'justificacion_modalidad_de']].drop_duplicates().reset_index(drop=True)
dim_detalles["id_detalles"] = dim_detalles.apply(lambda _: str(uuid.uuid4()), axis=1)
dim_detalles = dim_detalles[["id_detalles", "id_contrato", "referencia_del_contrato", "estado_contrato", "codigo_de_categoria_principal", "descripcion_del_proceso", "tipo_de_contrato", "modalidad_de_contratacion", "justificacion_modalidad_de"]]
dim_detalles

,id_detalles,id_contrato,referencia_del_contrato,estado_contrato,codigo_de_categoria_principal,descripcion_del_proceso,tipo_de_contrato,modalidad_de_contratacion,justificacion_modalidad_de
0,ffd73fe4-df7f-42ab-be30-92503ad2e1b2,CO1.PCCNTR.8560835,PE-CE-124-2025,Cerrado,V1.86132000,AUNAR ESFUERZOS ACADÉMICOS ENTRE LA PERSONERÍA...,Decreto 092 de 2017,Contratación régimen especial,Decreto 092 de 2017
1,2b8c3b86-07ca-4e4f-aaee-ed2f6822b106,CO1.PCCNTR.5846057,CO1.PCCNTR.5846057,Cerrado,V1.86101501,PRESTAR SERVICIOS PERSONALES DE CARÁCTER TEMPO...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
2,02b9bbf9-387a-4be0-b8f5-846ba09cd440,CO1.PCCNTR.1839307,202000000673,Cerrado,V1.80111600,EL CONTRATISTA SE OBLIGA CON EL DEPARTAMENTO D...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
3,c985ec7d-f9a5-4c5f-a796-30b6ce7f9332,CO1.PCCNTR.8627960,CO1.PCCNTR.8627960,Modificado,V1.44121701,PRESTAR DE MANERA INTEGRAL LOS SERVICIOS DE OP...,Prestación de servicios,Mínima cuantía,Presupuesto inferior al 10% de la menor cuantía
4,c7bd85c0-5109-4ab6-99d4-f7f5c1dfa638,CO1.PCCNTR.7096520,2388 DE 2024,En ejecución,V1.80111600,PRESTAR POR SUS PROPIOS MEDIOS; CON PLENA AUTO...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
...,...,...,...,...,...,...,...,...,...
1837,e5af5d43-aabf-4f5c-831c-420c5ecee8b2,CO1.PCCNTR.277825,CO1.PCCNTR.277825,cedido,V1.80111600,EL CONTRATISTA SE OBLIGA PARA CON EL MINISTERI...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
1838,e3da154f-f92b-4194-aa41-e13679de893f,CO1.PCCNTR.4689252,CO1.PCCNTR.4689252,terminado,V1.80111620,PRESTACIÓN DE SERVICIOS PERSONALES DE CARÁCTE...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
1839,9e26c827-d7a2-495c-aed5-7c4f3121f184,CO1.PCCNTR.9153527,ENV-15-09-0959-26,En ejecución,V1.80111600,PRESTACIÓN DE SERVICIOS TÉCNICOS ADMINISTRATIV...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
1840,ef6cf310-ad79-4cf1-a877-2dcf8316969f,CO1.PCCNTR.3229533,CD-59-2022-2613,En ejecución,V1.80111600,PRESTACION DE SERVICIOS DE APOYO A LA GESTION ...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
1841,f90167f5-1ea7-4c78-8735-2ea87be9759b,CO1.PCCNTR.4010790,CONTRATO 358 DE 2022,En ejecución,V1.80111701,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión

### Dim Cuenta

In [78]:
dim_cuenta = data[['id_contrato', 'nombre_del_banco', 'tipo_de_cuenta', 'numero_de_cuenta']]
dim_cuenta["id_cuenta"] = dim_cuenta.apply(lambda _: str(uuid.uuid4()), axis=1)
dim_cuenta = dim_cuenta[["id_cuenta", "id_contrato", "nombre_del_banco", "tipo_de_cuenta", "numero_de_cuenta"]]
dim_cuenta

,id_cuenta,id_contrato,nombre_del_banco,tipo_de_cuenta,numero_de_cuenta
0,7daa3c06-9371-4c4c-b8cf-191732517d93,CO1.PCCNTR.8560835,No definido,No Definido,No definido
1,dce25bff-042f-44cc-9176-c5775ae1929e,CO1.PCCNTR.5846057,BANCOLOMBIA,Ahorros,59781385268
2,ac5a142c-2429-4826-b571-ac56ed9a31d5,CO1.PCCNTR.1839307,BANCO BANCOLOMBIA,Ahorros,46600050702
3,8cf072ed-d9b5-474e-9d1e-791c873eecfb,CO1.PCCNTR.8627960,No definido,No Definido,No definido
4,71186566-4d5f-41a0-ba27-9dfa70aec1b4,CO1.PCCNTR.7096520,No definido,No Definido,No definido
...,...,...,...,...,...
1837,dc34231d-c7c1-4794-9d9d-fbf127e43e04,CO1.PCCNTR.277825,BANCOLOMBIA,Ahorros,66866801011
1838,a619a2f3-5354-444d-b2a2-f621067b7085,CO1.PCCNTR.4689252,No definido,No Definido,No definido
1839,2a37f34e-f0b0-4964-9fcd-cd686d907340,CO1.PCCNTR.9153527,No definido,No Definido,No definido
1840,4610d94d-d25a-4786-a592-7566609bd4d5,CO1.PCCNTR.3229533,No definido,No Definido,No definido
1841,96ec2224-6125-4c03-aefd-e188270c1b1d,CO1.PCCNTR.4010790,BANCOLOMBIA,Ahorros,84130617751

### Dim Representante

In [79]:
dim_representante = data[['id_contrato', 'identificacion_representante_legal', 'nombre_representante_legal', 'nacionalidad_representante_legal', 'domicilio_representante_legal', 'tipo_identificacion_representante_legal','genero_representante_legal']].drop_duplicates().reset_index(drop=True)
dim_representante["id_representante"] = dim_representante.apply(lambda _: str(uuid.uuid4()), axis=1)
dim_representante = dim_representante[["id_representante", "id_contrato", "identificacion_representante_legal", "nombre_representante_legal", "nacionalidad_representante_legal", "domicilio_representante_legal", "tipo_identificacion_representante_legal", "genero_representante_legal"]]
dim_representante

,id_representante,id_contrato,identificacion_representante_legal,nombre_representante_legal,nacionalidad_representante_legal,domicilio_representante_legal,tipo_identificacion_representante_legal,genero_representante_legal
0,f0b0185d-2743-4c37-8f03-06abbf0118df,CO1.PCCNTR.8560835,53154618,MARIA ANGELICA PAEZ,CO,Calle 8 No. 5 - 80,Cédula de Ciudadanía,Hombre
1,2cd3d498-82b3-40ed-b306-709806635f37,CO1.PCCNTR.5846057,1110506996,ROBERT JAVIER BONILLA PERALTA,CO,"Cra 9#135-25, Torre 1 apartamento 403 ibanazca",Cédula de Ciudadanía,Mujer
2,b240a8d5-f1c1-4ff6-9476-f7074840835b,CO1.PCCNTR.1839307,7572283,JUAN CARLOS MORA TORRES,CO,Mz C Casa 10 Urbanizacion Altavista,Cédula de Ciudadanía,No Definido
3,e29195c9-d5dd-4754-bc12-0e60492c08da,CO1.PCCNTR.8627960,Sin Descripcion,LILLY HAIDY BALAGUERA RODRIGUEZ,CO,No Definido,Sin Descripcion,Mujer
4,f31e7c36-6982-43ea-8db7-cef59240c893,CO1.PCCNTR.7096520,Sin Descripcion,EDWIN YESID SARMIENTO GUTIERREZ,CO,No Definido,Sin Descripcion,Otro
...,...,...,...,...,...,...,...,...
1837,977b3e30-35fd-4789-8c9f-e1d46416b08e,CO1.PCCNTR.277825,1013608939,LEONARDO VILLARREAL,CO,Calle 8 Sur 10 - 25,Cédula de Ciudadanía,No Definido
1838,8a778509-93d8-4136-a91d-02ff7f931803,CO1.PCCNTR.4689252,51760770,MARÍA JACQUELINE PAZMIÑO ANDRADE,CO,No Definido,Cédula de Ciudadanía,Mujer
1839,95b3a3d8-0544-479e-a8e6-544d6702751c,CO1.PCCNTR.9153527,Sin Descripcion,PATRICIA TEJADA,CO,cra 42 #39C49,Sin Descripcion,Mujer
1840,8f58ab05-2c38-44b4-ae13-c0fbea912017,CO1.PCCNTR.3229533,Sin Descripcion,FRANCELI VILLAREAL CARDENAS,CO,No Definido,Sin Descripcion,Mujer
1841,a85efd70-193f-40af-bcb1-e17c7207ff4d,CO1.PCCNTR.4010790,Sin Descripcion,JAN FRANCO AGUILERA ACOSTA,CO,No Definido,Sin Descripcion,Hombre

### Dim Características Generales

In [80]:
dim_caracteristicas_generales = data[['es_grupo', 'es_pyme', 'liquidacion', 'oblicacion_ambiental', 'espostconflicto', 'origen_de_los_recursos', 'destino_gasto']].drop_duplicates().reset_index(drop=True)
dim_caracteristicas_generales["id_caracteristicas_generales"] = dim_caracteristicas_generales.index + 1
dim_caracteristicas_generales = dim_caracteristicas_generales[["id_caracteristicas_generales", "es_grupo", "es_pyme", "liquidacion", "oblicacion_ambiental", "espostconflicto", "origen_de_los_recursos", "destino_gasto"]]
dim_caracteristicas_generales

,id_caracteristicas_generales,es_grupo,es_pyme,liquidacion,oblicacion_ambiental,espostconflicto,origen_de_los_recursos,destino_gasto
0,1,False,False,False,False,False,Distribuido,Funcionamiento
1,2,False,False,False,True,False,Distribuido,Inversión
2,3,False,False,False,False,False,Distribuido,Inversión
3,4,False,True,True,False,False,Distribuido,Inversión
4,5,False,False,False,False,False,Recursos Propios,Funcionamiento
5,6,False,False,False,False,False,Recursos Propios,Inversión
6,7,False,True,False,False,False,Distribuido,Inversión
7,8,False,False,True,False,False,Recursos Propios,Funcionamiento
8,9,False,False,False,False,True,Distribuido,Funcionamiento
9,10,False,False,True,False,False,Distribuido,Funcionamiento
10,11,False,True,False,False,False,Distribuido,Funcionamiento
11,12,False,True,False,False,False,Recursos Propios,Inversión
12,13,False,True,False,False,False,Recursos Propios,Funcionamiento
13,14,False,False,True,False,False,Distribuido,Inversión
14,15,False,True,True,False,False,Distribuido,Funcionamiento
15,16,False,True,True,False,False,Recursos Propios,Funcionamiento
16,17,False,False,True,False,False,Recursos Propios,Inversión
17,18,False,False,False,False,False,Distribuido,No Definido
18,19,False,False,False,False,True,Distribuido,Inversión
19,20,True,True,False,False,False,Distribuido,Funcionamiento
20,21,True,False,True,False,False,Distribuido,Funcionamiento
21,22,True,False,False,False,False,Distribuido,Funcionamiento
22,23,False,False,True,True,False,Distribuido,Inversión
23,24,False,False,False,True,False,Distribuido,Funcionamiento
24,25,False,False,False,True,False,Recursos Propios,Inversión
25,26,False,False,True,False,False,Distribuido,No Definido
26,27,False,True,False,False,False,Distribuido,No Definido
27,28,False,False,False,True,False,Recursos Propios,Funcionamiento
28,29,True,False,True,True,False,Distribuido,Funcionamiento
29,30,False,True,True,False,False,Recursos Propios,Inversión
30,31,False,True,False,True,False,Distribuido,Inversión
31,32,False,True,True,True,True,Distribuido,Funcionamiento
32,33,True,False,True,False,False,Recursos Propios,Inversión
33,34,False,True,True,False,False,Distribuido,No Definido
34,35,True,False,True,False,False,Distribuido,Inversión
35,36,False,False,False,False,True,Recursos Propios,Inversión
36,37,False,False,True,True,False,Distribuido,Funcionamiento
37,38,False,True,False,False,True,Distribuido,Inversión

### Dim Proveedor

In [82]:
dim_proveedor = data[['id_contrato', 'codigo_proveedor', 'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado']].drop_duplicates().reset_index(drop=True)
dim_proveedor

,id_contrato,codigo_proveedor,tipodocproveedor,documento_proveedor,proveedor_adjudicado
0,CO1.PCCNTR.8560835,702951591,NIT,860013798,UNIVERSIDAD LIBRE
1,CO1.PCCNTR.5846057,711134106,Cédula de Ciudadanía,1110506996,ROBERT JAVIER BONILLA PERALTA
2,CO1.PCCNTR.1839307,710003146,Cédula de Ciudadanía,7572283,JUAN CARLOS MORA TORRES
3,CO1.PCCNTR.8627960,722154051,Cédula de Ciudadanía,52822142,LILLY HAIDY BALAGUERA RODRIGUEZ
4,CO1.PCCNTR.7096520,724509872,Cédula de Ciudadanía,80110048,EDWIN YESID SARMIENTO GUTIERREZ
...,...,...,...,...,...
1837,CO1.PCCNTR.277825,705411239,Cédula de Ciudadanía,1013608939,ELKIN LEONARDO VILLARREAL VILLAMIZAR
1838,CO1.PCCNTR.4689252,710280116,Cédula de Ciudadanía,51760770,MARÍA JACQUELINE PAZMIÑO ANDRADE
1839,CO1.PCCNTR.9153527,713292241,Cédula de Ciudadanía,42937049,PATRICIA TEJADA
1840,CO1.PCCNTR.3229533,714234267,Cédula de Ciudadanía,52737792,FRANCELI VILLAREAL CARDENAS
1841,CO1.PCCNTR.4010790,716618046,Cédula de Ciudadanía,1006876651,JAN FRANCO AGUILERA ACOSTA

### Fact Table

In [83]:
fact_contrato = data[['id_contrato', 'codigo_proveedor', 'fecha_de_firma', 'fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato', 'valor_del_contrato', 'valor_de_pago_adelantado', 'valor_facturado', 'valor_pendiente_de_pago', 'valor_pagado', 'valor_amortizado', 'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 'saldo_cdp', 'saldo_vigencia', 'departamento', 'ciudad', 'es_grupo', 'es_pyme', 'liquidacion', 'oblicacion_ambiental', 'espostconflicto', 'origen_de_los_recursos', 'destino_gasto']]

lookup_geografia = dim_geografia.set_index(['departamento', 'ciudad'])['id_geografia'].to_dict()
fact_contrato['id_geografia'] = fact_contrato.apply(lambda row: lookup_geografia.get((row['departamento'], row['ciudad'])), axis=1)

fact_contrato = fact_contrato.drop(columns=['departamento', 'ciudad'])

lookup_cuenta = dim_cuenta.set_index('id_contrato')['id_cuenta'].to_dict()
fact_contrato['id_cuenta'] = fact_contrato['id_contrato'].map(lookup_cuenta)

lookup_detalles = dim_detalles.set_index('id_contrato')['id_detalles'].to_dict()
fact_contrato['id_detalles'] = fact_contrato['id_contrato'].map(lookup_detalles)

lookup_representante = dim_representante.set_index('id_contrato')['id_representante'].to_dict()
fact_contrato['id_representante'] = fact_contrato['id_contrato'].map(lookup_representante)

lookup_caracteristicas_generales = dim_caracteristicas_generales.set_index(['es_grupo', 'es_pyme', 'liquidacion', 'oblicacion_ambiental', 'espostconflicto', 'origen_de_los_recursos', 'destino_gasto'])['id_caracteristicas_generales'].to_dict()
fact_contrato['id_caracteristicas_generales'] = fact_contrato.apply(lambda row: lookup_caracteristicas_generales.get((row['es_grupo'], row['es_pyme'], row['liquidacion'], row['oblicacion_ambiental'], row['espostconflicto'], row['origen_de_los_recursos'], row['destino_gasto'])), axis=1)
fact_contrato = fact_contrato.drop(columns=['es_grupo', 'es_pyme', 'liquidacion', 'oblicacion_ambiental', 'espostconflicto', 'origen_de_los_recursos', 'destino_gasto'])

fact_contrato = fact_contrato[["id_contrato", "id_geografia", "id_cuenta", "id_detalles", "id_representante", "id_caracteristicas_generales", "codigo_proveedor", "fecha_de_firma", "fecha_de_inicio_del_contrato", "fecha_de_fin_del_contrato", "valor_del_contrato", "valor_de_pago_adelantado", "valor_facturado", "valor_pendiente_de_pago", "valor_pagado", "valor_amortizado", "valor_pendiente_de", "valor_pendiente_de_ejecucion", "saldo_cdp", "saldo_vigencia"]]

fact_contrato = fact_contrato.rename(columns={
    'codigo_proveedor': 'id_proveedor',
    'fecha_de_firma': 'id_fecha_firma',
    'fecha_de_inicio_del_contrato': 'id_fecha_inicio',
    'fecha_de_fin_del_contrato': 'id_fecha_fin',
    'valor_del_contrato': 'valor_contrato',
    'valor_de_pago_adelantado': 'valor_pago_adelantado',
})

fact_contrato

,id_contrato,id_geografia,id_cuenta,id_detalles,id_representante,id_caracteristicas_generales,id_proveedor,id_fecha_firma,id_fecha_inicio,id_fecha_fin,valor_contrato,valor_pago_adelantado,valor_facturado,valor_pendiente_de_pago,valor_pagado,valor_amortizado,valor_pendiente_de,valor_pendiente_de_ejecucion,saldo_cdp,saldo_vigencia
0,CO1.PCCNTR.8560835,a0873382-08c5-4535-ab71-6351f4f974c1,7daa3c06-9371-4c4c-b8cf-191732517d93,ffd73fe4-df7f-42ab-be30-92503ad2e1b2,f0b0185d-2743-4c37-8f03-06abbf0118df,1,702951591,2025-11-07,2025-11-07,2025-12-06,23076923,0,15000000,8076923,15000000,0,0,8076923,0,0
1,CO1.PCCNTR.5846057,55c91753-b900-484c-92f6-dc3bc0acadce,dce25bff-042f-44cc-9176-c5775ae1929e,2b8c3b86-07ca-4e4f-aaee-ed2f6822b106,2cd3d498-82b3-40ed-b306-709806635f37,2,711134106,2024-01-31,2024-02-01,2024-12-13,46532667,0,46532667,0,46532667,0,0,0,3493699470,0
2,CO1.PCCNTR.1839307,f0e48572-3f42-429b-a88c-580730891487,ac5a142c-2429-4826-b571-ac56ed9a31d5,02b9bbf9-387a-4be0-b8f5-846ba09cd440,b240a8d5-f1c1-4ff6-9476-f7074840835b,3,710003146,2020-09-17,2020-09-17,2020-12-30,23870000,0,23870000,0,23870000,0,0,0,0,0
3,CO1.PCCNTR.8627960,b21b339b-392f-437e-8ccc-92f1a4f79785,8cf072ed-d9b5-474e-9d1e-791c873eecfb,c985ec7d-f9a5-4c5f-a796-30b6ce7f9332,e29195c9-d5dd-4754-bc12-0e60492c08da,4,722154051,2025-11-24,2025-11-26,2025-12-12,33000000,0,32999204,33000000,0,0,0,33000000,0,0
4,CO1.PCCNTR.7096520,cbaea542-c3b3-4700-bf9d-3dc480472d2f,71186566-4d5f-41a0-ba27-9dfa70aec1b4,c7bd85c0-5109-4ab6-99d4-f7f5c1dfa638,f31e7c36-6982-43ea-8db7-cef59240c893,3,724509872,2024-12-03,2024-12-06,2024-12-31,9000000,0,0,9000000,0,0,0,9000000,13500000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1837,CO1.PCCNTR.277825,cbaea542-c3b3-4700-bf9d-3dc480472d2f,dc34231d-c7c1-4794-9d9d-fbf127e43e04,e5af5d43-aabf-4f5c-831c-420c5ecee8b2,977b3e30-35fd-4789-8c9f-e1d46416b08e,1,705411239,2018-01-12,2018-01-09,2018-11-20,32865000,0,0,32865000,0,0,0,32865000,32865000,0
1838,CO1.PCCNTR.4689252,cbaea542-c3b3-4700-bf9d-3dc480472d2f,a619a2f3-5354-444d-b2a2-f621067b7085,e3da154f-f92b-4194-aa41-e13679de893f,8a778509-93d8-4136-a91d-02ff7f931803,1,710280116,2023-02-24,2023-02-27,2023-10-11,30726225,0,30726225,0,30726225,0,0,0,754226704,0
1839,CO1.PCCNTR.9153527,cfaa318a-0dc3-4151-8628-3a45a819b73d,2a37f34e-f0b0-4964-9fcd-cd686d907340,9e26c827-d7a2-495c-aed5-7c4f3121f184,95b3a3d8-0544-479e-a8e6-544d6702751c,3,713292241,2026-01-26,2026-02-02,2026-12-15,41783310,0,0,41783310,0,0,0,41783310,0,0
1840,CO1.PCCNTR.3229533,c39144f5-1cda-4746-ad21-e3e8cab68721,4610d94d-d25a-4786-a592-7566609bd4d5,ef6cf310-ad79-4cf1-a877-2dcf8316969f,8f58ab05-2c38-44b4-ae13-c0fbea912017,3,714234267,2022-01-14,2022-01-18,2022-07-17,10926000,0,10926000,10926000,0,0,0,10926000,2731500000,0
1841,CO1.PCCNTR.4010790,e58db15f-39e2-481a-9c67-f151b60ae251,96ec2224-6125-4c03-aefd-e188270c1b1d,f90167f5-1ea7-4c78-8735-2ea87be9759b,a85efd70-193f-40af-bcb1-e17c7207ff4d,3,716618046,2022-09-09,2022-09-09,2022-12-23,7000000,0,7000000,5000000,2000000,0,0,5000000,7000000,0

#### Correción dimensiones

In [84]:
dim_cuenta = dim_cuenta.drop(columns=['id_contrato'])
dim_cuenta = dim_cuenta.rename(columns={'nombre_del_banco': 'banco', 'tipo_de_cuenta': 'tipo_cuenta', 'numero_de_cuenta': 'numero_cuenta'})
dim_cuenta

,id_cuenta,banco,tipo_cuenta,numero_cuenta
0,7daa3c06-9371-4c4c-b8cf-191732517d93,No definido,No Definido,No definido
1,dce25bff-042f-44cc-9176-c5775ae1929e,BANCOLOMBIA,Ahorros,59781385268
2,ac5a142c-2429-4826-b571-ac56ed9a31d5,BANCO BANCOLOMBIA,Ahorros,46600050702
3,8cf072ed-d9b5-474e-9d1e-791c873eecfb,No definido,No Definido,No definido
4,71186566-4d5f-41a0-ba27-9dfa70aec1b4,No definido,No Definido,No definido
...,...,...,...,...
1837,dc34231d-c7c1-4794-9d9d-fbf127e43e04,BANCOLOMBIA,Ahorros,66866801011
1838,a619a2f3-5354-444d-b2a2-f621067b7085,No definido,No Definido,No definido
1839,2a37f34e-f0b0-4964-9fcd-cd686d907340,No definido,No Definido,No definido
1840,4610d94d-d25a-4786-a592-7566609bd4d5,No definido,No Definido,No definido
1841,96ec2224-6125-4c03-aefd-e188270c1b1d,BANCOLOMBIA,Ahorros,84130617751

In [85]:
dim_detalles = dim_detalles.drop(columns=['id_contrato'])
dim_detalles = dim_detalles.rename(columns={'referencia_del_contrato': 'referencia', 'estado_contrato': 'estado', 'codigo_de_categoria_principal': 'codigo_categoria_principal', 'descripcion_del_proceso': 'descripcion_proceso', 'tipo_de_contrato': 'tipo_contrato', 'modalidad_de_contratacion': 'modalidad_contratacion', 'justificacion_modalidad_de': 'justificacion_modalidad'})
dim_detalles

,id_detalles,referencia,estado,codigo_categoria_principal,descripcion_proceso,tipo_contrato,modalidad_contratacion,justificacion_modalidad
0,ffd73fe4-df7f-42ab-be30-92503ad2e1b2,PE-CE-124-2025,Cerrado,V1.86132000,AUNAR ESFUERZOS ACADÉMICOS ENTRE LA PERSONERÍA...,Decreto 092 de 2017,Contratación régimen especial,Decreto 092 de 2017
1,2b8c3b86-07ca-4e4f-aaee-ed2f6822b106,CO1.PCCNTR.5846057,Cerrado,V1.86101501,PRESTAR SERVICIOS PERSONALES DE CARÁCTER TEMPO...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
2,02b9bbf9-387a-4be0-b8f5-846ba09cd440,202000000673,Cerrado,V1.80111600,EL CONTRATISTA SE OBLIGA CON EL DEPARTAMENTO D...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
3,c985ec7d-f9a5-4c5f-a796-30b6ce7f9332,CO1.PCCNTR.8627960,Modificado,V1.44121701,PRESTAR DE MANERA INTEGRAL LOS SERVICIOS DE OP...,Prestación de servicios,Mínima cuantía,Presupuesto inferior al 10% de la menor cuantía
4,c7bd85c0-5109-4ab6-99d4-f7f5c1dfa638,2388 DE 2024,En ejecución,V1.80111600,PRESTAR POR SUS PROPIOS MEDIOS; CON PLENA AUTO...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
...,...,...,...,...,...,...,...,...
1837,e5af5d43-aabf-4f5c-831c-420c5ecee8b2,CO1.PCCNTR.277825,cedido,V1.80111600,EL CONTRATISTA SE OBLIGA PARA CON EL MINISTERI...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
1838,e3da154f-f92b-4194-aa41-e13679de893f,CO1.PCCNTR.4689252,terminado,V1.80111620,PRESTACIÓN DE SERVICIOS PERSONALES DE CARÁCTE...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
1839,9e26c827-d7a2-495c-aed5-7c4f3121f184,ENV-15-09-0959-26,En ejecución,V1.80111600,PRESTACIÓN DE SERVICIOS TÉCNICOS ADMINISTRATIV...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
1840,ef6cf310-ad79-4cf1-a877-2dcf8316969f,CD-59-2022-2613,En ejecución,V1.80111600,PRESTACION DE SERVICIOS DE APOYO A LA GESTION ...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión
1841,f90167f5-1ea7-4c78-8735-2ea87be9759b,CONTRATO 358 DE 2022,En ejecución,V1.80111701,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,Prestación de servicios,Contratación directa,Servicios profesionales y apoyo a la gestión

In [86]:
dim_representante = dim_representante.drop(columns=['id_contrato'])
dim_representante = dim_representante.rename(columns={'identificacion_representante_legal': 'identificacion', 'nombre_representante_legal': 'nombre', 'nacionalidad_representante_legal': 'nacionalidad', 'domicilio_representante_legal': 'domicilio', 'tipo_identificacion_representante_legal': 'tipo_identificacion', 'genero_representante_legal': 'genero'})
dim_representante

,id_representante,identificacion,nombre,nacionalidad,domicilio,tipo_identificacion,genero
0,f0b0185d-2743-4c37-8f03-06abbf0118df,53154618,MARIA ANGELICA PAEZ,CO,Calle 8 No. 5 - 80,Cédula de Ciudadanía,Hombre
1,2cd3d498-82b3-40ed-b306-709806635f37,1110506996,ROBERT JAVIER BONILLA PERALTA,CO,"Cra 9#135-25, Torre 1 apartamento 403 ibanazca",Cédula de Ciudadanía,Mujer
2,b240a8d5-f1c1-4ff6-9476-f7074840835b,7572283,JUAN CARLOS MORA TORRES,CO,Mz C Casa 10 Urbanizacion Altavista,Cédula de Ciudadanía,No Definido
3,e29195c9-d5dd-4754-bc12-0e60492c08da,Sin Descripcion,LILLY HAIDY BALAGUERA RODRIGUEZ,CO,No Definido,Sin Descripcion,Mujer
4,f31e7c36-6982-43ea-8db7-cef59240c893,Sin Descripcion,EDWIN YESID SARMIENTO GUTIERREZ,CO,No Definido,Sin Descripcion,Otro
...,...,...,...,...,...,...,...
1837,977b3e30-35fd-4789-8c9f-e1d46416b08e,1013608939,LEONARDO VILLARREAL,CO,Calle 8 Sur 10 - 25,Cédula de Ciudadanía,No Definido
1838,8a778509-93d8-4136-a91d-02ff7f931803,51760770,MARÍA JACQUELINE PAZMIÑO ANDRADE,CO,No Definido,Cédula de Ciudadanía,Mujer
1839,95b3a3d8-0544-479e-a8e6-544d6702751c,Sin Descripcion,PATRICIA TEJADA,CO,cra 42 #39C49,Sin Descripcion,Mujer
1840,8f58ab05-2c38-44b4-ae13-c0fbea912017,Sin Descripcion,FRANCELI VILLAREAL CARDENAS,CO,No Definido,Sin Descripcion,Mujer
1841,a85efd70-193f-40af-bcb1-e17c7207ff4d,Sin Descripcion,JAN FRANCO AGUILERA ACOSTA,CO,No Definido,Sin Descripcion,Hombre

In [87]:
dim_proveedor = dim_proveedor.drop(columns=['id_contrato'])
dim_proveedor = dim_proveedor.rename(columns={'codigo_proveedor': 'id_proveedor', 'tipodocproveedor': 'tipo_documento', 'documento_proveedor': 'documento', 'proveedor_adjudicado': 'nombre'})
dim_proveedor

,id_proveedor,tipo_documento,documento,nombre
0,702951591,NIT,860013798,UNIVERSIDAD LIBRE
1,711134106,Cédula de Ciudadanía,1110506996,ROBERT JAVIER BONILLA PERALTA
2,710003146,Cédula de Ciudadanía,7572283,JUAN CARLOS MORA TORRES
3,722154051,Cédula de Ciudadanía,52822142,LILLY HAIDY BALAGUERA RODRIGUEZ
4,724509872,Cédula de Ciudadanía,80110048,EDWIN YESID SARMIENTO GUTIERREZ
...,...,...,...,...
1837,705411239,Cédula de Ciudadanía,1013608939,ELKIN LEONARDO VILLARREAL VILLAMIZAR
1838,710280116,Cédula de Ciudadanía,51760770,MARÍA JACQUELINE PAZMIÑO ANDRADE
1839,713292241,Cédula de Ciudadanía,42937049,PATRICIA TEJADA
1840,714234267,Cédula de Ciudadanía,52737792,FRANCELI VILLAREAL CARDENAS
1841,716618046,Cédula de Ciudadanía,1006876651,JAN FRANCO AGUILERA ACOSTA